OC: OClog Management
OClog Management
Functions
void ocloginit (void)
int ocsetlogging (int tf)
int oclogopen (const char *file)
void oclogclose (void)
void oclog (int tag, const char *fmt,...)
void oclogtext (int tag, const char *text)
void oclogtextn (int tag, const char *text, size_t count)
void oclogsettags (char **tagset, char *dfalt)
Detailed Description
Function Documentation
void oclog (int tag, const char * fmt, ...)
Send logging messages. This uses a variable number of arguments and operates like the stdio printf function.
Parameters
[in] tag Indicate the kind of this log message.
[in] fmt Format specification as with printf.
Definition at line 159 of file oclog.c.
References ocloginit().
void oclogclose (void)
Definition at line 137 of file oclog.c.
References ocloginit().
Referenced by oclogopen().
void ocloginit (void)
Definition at line 46 of file oclog.c.
References oclogopen(), ocsetlogging(), and OCTAGDFALT.
Referenced by oclog(), oclogclose(), oclogopen(), and ocsetlogging().
int oclogopen (const char * file)
Specify a file into which to place logging output.
Parameters
[in] file The name of the file into which to place logging output. If the file has the value NULL, then send logging output to stderr.
Returns
zero if the open failed, one otherwise.
Definition at line 96 of file oclog.c.
References oclogclose(), ocloginit(), and ocsetlogging().
Referenced by ocloginit().
void oclogsettags (char ** tagset, char * dfalt)
Definition at line 205 of file oclog.c.
References MAXTAGS.
void oclogtext (int tag, const char * text)
Definition at line 181 of file oclog.c.
References oclogtextn().
void oclogtextn (int tag, const char * text, size_t count)
Send arbitrarily long text as a logging message. Each line will be sent using oclog with the specified tag.
Parameters
[in] tag Indicate the kind of this log message.
[in] text Arbitrary text to send as a logging message.
[in] count Maximum ength of the text to write.
Definition at line 196 of file oclog.c.
Referenced by oclogtext().
int ocsetlogging (int tf)
Enable/Disable logging.
Parameters
[in] tf If 1, then turn on logging, if 0, then turn off logging.
Returns
The previous value of the logging flag.
Definition at line 76 of file oclog.c.
References ocloginit().
Referenced by ocloginit(), and oclogopen().