#!/bin/bash
#X="-x"
#NB=1

DBG=1

# Use only if default is not correct
#M32=1
#M64=1

if test $# != 0 ; then
cmds=$@
fi

if test "x$MAKE" = x ; then
MAKE=make
fi

CFLAGS="-g -O0"
#CFLAGS="-Wall -Wno-unused-variable -Wno-unused-parameter -Wconversion ${CFLAGS}"
#CFLAGS="-Wall -Wno-unused-variable -Wno-unused-parameter ${CFLAGS}"
#CFLAGS="-Wconversion"

stddir="/usr/local"
PREFIX=/usr/local

if test "x${cmds}" = x ; then
  cmds=""
else
for f in $cmds ; do
  if test "x$f" = "xdistcheck" ; then
    PREFIX=/tmp/$HOST
  fi
done
fi

if test x$M32 = x1 ; then
CFLAGS="-m32 $CFLAGS"
fi
if test x$M64 = x1 ; then
CFLAGS="-m64 $CFLAGS"
fi

# If curl-config is in path, then make no attempt to override
if curl-config --version >/dev/null ; then
TMP=`curl-config --cflags`
CPPFLAGS="$TMP $CPPFLAGS"
TMP=`curl-config --libs`
LDFLAGS="$TMP $LDFLAGS"
TMP=`curl-config --prefix`
LD_LIBRARY_PATH="$TMP/lib:$LD_LIBRARY_PATH"
else
  echo "Cannot find curl-config"
  exit 1
fi

FLAGS="--prefix ${PREFIX}"
FLAGS="${FLAGS} --enable-remote-tests"
FLAGS="${FLAGS} --enable-auth-tests"
#FLAGS="${FLAGS} --enable-idl-code"
#FLAGS="${FLAGS} --disable-disk_storage"
#FLAGS="${FLAGS} --enable-xgetopt"
#if test x$CURLCONFIG != x ; then
#FLAGS="$FLAGS --with-curl-config=$CURLCONFIG"
#fi

if test "x$DBG" == x ; then
FLAGS="${FLAGS} --enable-shared"
else
FLAGS="${FLAGS} --disable-shared"
fi

LIBS="$LIBS /share/ed/local/spike/lib/libcurl.a"

export PATH
export CC
export CPPFLAGS
export CFLAGS
export LDFLAGS
export LD_LIBRARY_PATH

DISTCHECK_CONFIGURE_FLAGS="$FLAGS"; export DISTCHECK_CONFIGURE_FLAGS

if test -z "$NB" ; then
${MAKE} -i maintainer-clean >/dev/null 2>&1
if autoreconf -i --force ; then ok=1; else exit ; fi
fi

if test -f Makefile ; then ${MAKE} distclean >/dev/null 2>&1 ; fi
sh $X ./configure ${FLAGS}
for c in $cmds; do
  ${MAKE} $c
done
exit 0
